//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.ETicaretWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KategorilerResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class KategorilerResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        private System.Nullable<int> UstKategoriIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> UstKategoriId {
            get {
                return this.UstKategoriIdField;
            }
            set {
                if ((this.UstKategoriIdField.Equals(value) != true)) {
                    this.UstKategoriIdField = value;
                    this.RaisePropertyChanged("UstKategoriId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ETicaretWebService.ETicaretWebServiceSoap")]
    public interface ETicaretWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ETicaret.ETicaretWebService.HelloWorldResponse HelloWorld(ETicaret.ETicaretWebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ETicaret.ETicaretWebService.HelloWorldResponse> HelloWorldAsync(ETicaret.ETicaretWebService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name KategorileriGetirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KategorileriGetir", ReplyAction="*")]
        ETicaret.ETicaretWebService.KategorileriGetirResponse KategorileriGetir(ETicaret.ETicaretWebService.KategorileriGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KategorileriGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<ETicaret.ETicaretWebService.KategorileriGetirResponse> KategorileriGetirAsync(ETicaret.ETicaretWebService.KategorileriGetirRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ETicaret.ETicaretWebService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ETicaret.ETicaretWebService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ETicaret.ETicaretWebService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ETicaret.ETicaretWebService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KategorileriGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KategorileriGetir", Namespace="http://tempuri.org/", Order=0)]
        public ETicaret.ETicaretWebService.KategorileriGetirRequestBody Body;
        
        public KategorileriGetirRequest() {
        }
        
        public KategorileriGetirRequest(ETicaret.ETicaretWebService.KategorileriGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class KategorileriGetirRequestBody {
        
        public KategorileriGetirRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KategorileriGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KategorileriGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public ETicaret.ETicaretWebService.KategorileriGetirResponseBody Body;
        
        public KategorileriGetirResponse() {
        }
        
        public KategorileriGetirResponse(ETicaret.ETicaretWebService.KategorileriGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KategorileriGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ETicaret.ETicaretWebService.KategorilerResult> KategorileriGetirResult;
        
        public KategorileriGetirResponseBody() {
        }
        
        public KategorileriGetirResponseBody(System.Collections.Generic.List<ETicaret.ETicaretWebService.KategorilerResult> KategorileriGetirResult) {
            this.KategorileriGetirResult = KategorileriGetirResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ETicaretWebServiceSoapChannel : ETicaret.ETicaretWebService.ETicaretWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ETicaretWebServiceSoapClient : System.ServiceModel.ClientBase<ETicaret.ETicaretWebService.ETicaretWebServiceSoap>, ETicaret.ETicaretWebService.ETicaretWebServiceSoap {
        
        public ETicaretWebServiceSoapClient() {
        }
        
        public ETicaretWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ETicaretWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ETicaretWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ETicaretWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ETicaret.ETicaretWebService.HelloWorldResponse ETicaret.ETicaretWebService.ETicaretWebServiceSoap.HelloWorld(ETicaret.ETicaretWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ETicaret.ETicaretWebService.HelloWorldRequest inValue = new ETicaret.ETicaretWebService.HelloWorldRequest();
            inValue.Body = new ETicaret.ETicaretWebService.HelloWorldRequestBody();
            ETicaret.ETicaretWebService.HelloWorldResponse retVal = ((ETicaret.ETicaretWebService.ETicaretWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ETicaret.ETicaretWebService.HelloWorldResponse> ETicaret.ETicaretWebService.ETicaretWebServiceSoap.HelloWorldAsync(ETicaret.ETicaretWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ETicaret.ETicaretWebService.HelloWorldResponse> HelloWorldAsync() {
            ETicaret.ETicaretWebService.HelloWorldRequest inValue = new ETicaret.ETicaretWebService.HelloWorldRequest();
            inValue.Body = new ETicaret.ETicaretWebService.HelloWorldRequestBody();
            return ((ETicaret.ETicaretWebService.ETicaretWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ETicaret.ETicaretWebService.KategorileriGetirResponse ETicaret.ETicaretWebService.ETicaretWebServiceSoap.KategorileriGetir(ETicaret.ETicaretWebService.KategorileriGetirRequest request) {
            return base.Channel.KategorileriGetir(request);
        }
        
        public System.Collections.Generic.List<ETicaret.ETicaretWebService.KategorilerResult> KategorileriGetir() {
            ETicaret.ETicaretWebService.KategorileriGetirRequest inValue = new ETicaret.ETicaretWebService.KategorileriGetirRequest();
            inValue.Body = new ETicaret.ETicaretWebService.KategorileriGetirRequestBody();
            ETicaret.ETicaretWebService.KategorileriGetirResponse retVal = ((ETicaret.ETicaretWebService.ETicaretWebServiceSoap)(this)).KategorileriGetir(inValue);
            return retVal.Body.KategorileriGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ETicaret.ETicaretWebService.KategorileriGetirResponse> ETicaret.ETicaretWebService.ETicaretWebServiceSoap.KategorileriGetirAsync(ETicaret.ETicaretWebService.KategorileriGetirRequest request) {
            return base.Channel.KategorileriGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ETicaret.ETicaretWebService.KategorileriGetirResponse> KategorileriGetirAsync() {
            ETicaret.ETicaretWebService.KategorileriGetirRequest inValue = new ETicaret.ETicaretWebService.KategorileriGetirRequest();
            inValue.Body = new ETicaret.ETicaretWebService.KategorileriGetirRequestBody();
            return ((ETicaret.ETicaretWebService.ETicaretWebServiceSoap)(this)).KategorileriGetirAsync(inValue);
        }
    }
}
